services:
  - type: web
    name: solar
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: DB_HOST
        fromService:
          name: mysql-service
          type: pserv
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: solar_db
      - key: DB_USER
        value: solar_user
      - key: DB_PASSWORD
        value: solar_pass

  - type: pserv
    name: mysql-service
    env: docker
    plan: free
    dockerfilePath: ./mysql-docker/Dockerfile
